### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by TG1999** [codeuino/Codebadge#3]
### **Description of the problem**
There is no described Readme for this project for now
### **How to solve**
Please write a described readme like the DONUT project

### **Expected Outcome**
An explained readme so that user can know how to set up the project

Assigning this issue to @sarthak77

**Comment by sarthak77** [comment]
Ok will work on it

**Comment by TG1999** [comment]
Thanks @sarthak77

**Comment by jaskiratsingh2000** [comment]
Thanks Please go ahead for this
