### ISSUE TITLE
Create a new UI for upload route

### ISSUE THREAD

**Issue by ayushnagar123** [codeuino/Codebadge#42]
### **What you will need to know?**
HTML, CSS, JavaScript,Vuejs.

### **Design UI for codebadge Illustrator**
We are willing t an illustrator for codebadge project. Your task is to design a UI design for new badge template upload route located on /upload. Alse needs to add button on /home which will redirect the user to /upload.

### **Pages you will need to update**
1. https://github.com/codeuino/Codebadge/blob/master/src/views/Upload.vue
2. https://github.com/codeuino/Codebadge/blob/master/src/views/HomeView.vue

### **Expected Outcome**
Create an attractive UI for /upload route using Vuejs.

### **Resources & References (Where to Start)**
You can go through CodeBadge project commit your code on [Codebadge development branch](https://github.com/codeuino/Codebadge)

Some reference material
https://vuejs.org/v2/guide/components.html
https://vuejs.org/v2/guide/components-props.html
https://bootstrap-vue.js.org/

### **Extras**
Just follow the readme whenever you are stuck. Visit [Codeuino's Slack Channel](https://codeuino.slack.com/) in case of any doubts.s Website](https://codeuino.slack.com/) in case of any doubts.

**Comment by aRealCyborg** [comment]
you might want to close this issue
